spring:
  application:
    name: "crm_programming_school"
  config:
    import: classpath:secrets.yaml
  datasource:
    url: ${MySQL.url}
    password: ${MySQL.password}
    username: ${MySQL.username}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
