spring:
  application:
    name: "crm_programming_school"
  config:
    import: classpath:secrets.yaml
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: ${MySQL.url}
    password: ${MySQL.password}
    username: ${MySQL.username}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 10MB
      enabled: true
#logging:
#  level:
#    liquibase: DEBUG
#    org.springframework.data.jpa: TRACE
#    org.springframework: DEBUG
#    com.zaxxer.hikari: DEBUG
